// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleApiTester.Infrastructure.Persistence;

#nullable disable

namespace SimpleApiTester.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260818101244_AddVariableIsSecret")]
    partial class AddVariableIsSecret
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SimpleApiTester.Domain.Entities.DataSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("DataSources");
                });

            modelBuilder.Entity("SimpleApiTester.Domain.Entities.DataSourceEnvironment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("DataSourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.HasKey("Id");

                    b.HasIndex("DataSourceId", "Name")
                        .IsUnique();

                    b.ToTable("DataSourceEnvironments");
                });

            modelBuilder.Entity("SimpleApiTester.Domain.Entities.Header", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DataSourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<Guid?>("OperationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceKey")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Value")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ValueSourceType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("DataSourceId", "Key")
                        .IsUnique()
                        .HasFilter("[DataSourceId] IS NOT NULL");

                    b.HasIndex("OperationId", "Key")
                        .IsUnique()
                        .HasFilter("[OperationId] IS NOT NULL");

                    b.ToTable("Headers", t =>
                        {
                            t.HasCheckConstraint("CK_Headers_ExactlyOneParent", "(([DataSourceId] IS NOT NULL AND [OperationId] IS NULL) OR ([DataSourceId] IS NULL AND [OperationId] IS NOT NULL))");

                            t.HasCheckConstraint("CK_Headers_ValueSourceShape", "(([ValueSourceType] = 'General' AND [Value] IS NOT NULL AND [SourceKey] IS NULL) OR ([ValueSourceType] <> 'General' AND [Value] IS NULL AND [SourceKey] IS NOT NULL))");
                        });
                });

            modelBuilder.Entity("SimpleApiTester.Domain.Entities.Operation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApiName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentType")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("DataSourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MethodType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("DataSourceId");

                    b.ToTable("Operations");
                });

            modelBuilder.Entity("SimpleApiTester.Domain.Entities.QueryParameter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("OperationId");

                    b.ToTable("QueryParameters");
                });

            modelBuilder.Entity("SimpleApiTester.Domain.Entities.Variable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DataSourceEnvironmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSecret")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Value")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("DataSourceEnvironmentId", "Key")
                        .IsUnique();

                    b.ToTable("Variables");
                });

            modelBuilder.Entity("SimpleApiTester.Domain.Entities.DataSourceEnvironment", b =>
                {
                    b.HasOne("SimpleApiTester.Domain.Entities.DataSource", "DataSource")
                        .WithMany("Environments")
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataSource");
                });

            modelBuilder.Entity("SimpleApiTester.Domain.Entities.Header", b =>
                {
                    b.HasOne("SimpleApiTester.Domain.Entities.DataSource", "DataSource")
                        .WithMany("Headers")
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SimpleApiTester.Domain.Entities.Operation", "Operation")
                        .WithMany("Headers")
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("DataSource");

                    b.Navigation("Operation");
                });

            modelBuilder.Entity("SimpleApiTester.Domain.Entities.Operation", b =>
                {
                    b.HasOne("SimpleApiTester.Domain.Entities.DataSource", "DataSource")
                        .WithMany("Operations")
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataSource");
                });

            modelBuilder.Entity("SimpleApiTester.Domain.Entities.QueryParameter", b =>
                {
                    b.HasOne("SimpleApiTester.Domain.Entities.Operation", "Operation")
                        .WithMany("QueryParameters")
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operation");
                });

            modelBuilder.Entity("SimpleApiTester.Domain.Entities.Variable", b =>
                {
                    b.HasOne("SimpleApiTester.Domain.Entities.DataSourceEnvironment", "DataSourceEnvironment")
                        .WithMany("Variables")
                        .HasForeignKey("DataSourceEnvironmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataSourceEnvironment");
                });

            modelBuilder.Entity("SimpleApiTester.Domain.Entities.DataSource", b =>
                {
                    b.Navigation("Environments");

                    b.Navigation("Headers");

                    b.Navigation("Operations");
                });

            modelBuilder.Entity("SimpleApiTester.Domain.Entities.DataSourceEnvironment", b =>
                {
                    b.Navigation("Variables");
                });

            modelBuilder.Entity("SimpleApiTester.Domain.Entities.Operation", b =>
                {
                    b.Navigation("Headers");

                    b.Navigation("QueryParameters");
                });
#pragma warning restore 612, 618
        }
    }
}
